#!/bin/bash

# Script for running the selfhosted tests on QPUs directly from GitHub
# Tests need to be copied to /tmp/ because coverage does not work with NFS

cp -r tests /tmp/qibo
cp pyproject.toml /tmp/qibo
cd /tmp/qibo/tests
source /nfs/users/github/actions-runner/_work/qibo/qibo/testenv/bin/activate
pytest
pytest_status=$?
if [[ $pytest_status -ne 0 ]]
    then
        exit $pytest_status
fi
cd -
mv /tmp/qibo/tests/coverage.xml .
mv /tmp/qibo/tests/htmlcov .
rm -r /tmp/qibo/tests
