#!/bin/bash

# Script for running the selfhosted tests on QPUs directly from GitHub
# Tests need to be copied to /tmp/ because coverage does not work with NFS

tmpdir=/tmp/$(date +%s)
mkdir $tmpdir
cp -r tests $tmpdir
cp pyproject.toml $tmpdir
cd $tmpdir/tests
source /nfs/users/github/actions-runner/_work/qibo/qibo/testenv/bin/activate
pytest
pytest_status=$?
if [[ $pytest_status -ne 0 ]]
    then
        exit $pytest_status
fi
cd -
mv $tmpdir/tests/coverage.xml .
mv $tmpdir/tests/htmlcov .
rm -r $tmpdir
