"""Protected functions supporting quantum_info/linalg_operations.py"""

import math

import numpy as np
from numpy.typing import ArrayLike

from qibo.backends import Backend, CliffordBackend, _check_backend, _get_engine_name
from qibo.backends._clifford_operations import _exponent
from qibo.config import log, raise_error


def _gram_schmidt_process(
    vector: ArrayLike, directions: ArrayLike, backend: Backend | None = None
) -> ArrayLike:
    """Return an array that is orthogonal to the ``directions`` array(s).

    Args:
        vector (ArrayLike): vector to be orthogonalized.
        directions (ArrayLike): either an :math:`1`-dimensional array corresponding to the
            direction of projection or an array of arrays corresponding to several
            directions.
        backend (:class:`qibo.backends.abstract.Backend`, optional): backend to be
            used in the execution. If ``None``, it uses
            the current backend. Defaults to ``None``.

    Returns:
        ArrayLike: Array orthogonalized with respect to ``directions``.
    """
    backend = _check_backend(backend)

    if isinstance(directions, list):
        directions = backend.cast(directions, dtype=directions[0].dtype)

    projections = _vector_projection(vector, directions, backend=backend)

    if len(directions.shape) > 1:
        projections = backend.sum(projections, axis=0)

    return vector - projections


def _lie_closure_matrix(
    generators: list[ArrayLike],
    max_iterations: int,
    tol: float,
    backend: Backend | None = None,
) -> ArrayLike:
    """Compute the dynamical Lie algebra generated by Hermitian or skew-Hermitian matrices.

    Args:
        generators (list[ArrayLike]): square matrices of identical shape.
        max_iterations (int): maximum nesting depth of commutators.
        tol (float): threshold on the Frobenius norm below which a candidate
            is considered linearly dependent on the current basis.
        backend (:class:`qibo.backends.abstract.Backend`, optional): backend to be
            used in the execution. If ``None``, it uses the current backend.
            Defaults to ``None``.

    Returns:
        ArrayLike: Array of shape ``(dim, d, d)`` with an orthonormal Hermitian basis.
    """
    backend = _check_backend(backend)

    generators = [backend.cast(gen, dtype=backend.complex128) for gen in generators]

    if len(generators) == 0 or any(
        len(gen.shape) != 2
        or gen.shape[0] != gen.shape[1]
        or gen.shape != generators[0].shape
        for gen in generators
    ):
        raise_error(
            TypeError,
            "``generators`` must be a non-empty list of square matrices "
            + "with the same shape.",
        )

    candidates = []
    for gen in generators:
        dagger = backend.transpose(backend.conj(gen))
        if backend.allclose(gen, dagger):
            candidates.append(gen)
        elif backend.allclose(gen, -dagger):
            candidates.append(1j * gen)
        else:
            raise_error(
                ValueError, "All ``generators`` must be Hermitian or skew-Hermitian."
            )

    dims = generators[0].shape[0]
    basis = backend.zeros((0, dims, dims), dtype=backend.complex128)
    nb_generators = 0
    smallest = math.inf
    for epoch in range(max_iterations + 1):
        old_length = basis.shape[0]

        # Gram-Schmidt with respect to the Hilbert-Schmidt inner product,
        # repeated twice for numerical stability
        for candidate in candidates:
            for _ in range(2):
                overlaps = backend.einsum("kij,ij->k", backend.conj(basis), candidate)
                candidate = candidate - backend.einsum("k,kij->ij", overlaps, basis)
            norm = backend.matrix_norm(candidate, order="fro")
            if norm > tol:
                if epoch > 0:
                    smallest = min(smallest, float(norm))
                candidate = backend.reshape(candidate / norm, (1, dims, dims))
                basis = backend.concatenate((basis, candidate))

        if basis.shape[0] == old_length:
            break

        if epoch == 0:
            nb_generators = basis.shape[0]

        # the commutator of Hermitian operators is skew-Hermitian,
        # thus the factor of 1j to keep the basis Hermitian
        candidates = 1j * (
            backend.einsum("aij,bjk->abik", basis[old_length:], basis[:nb_generators])
            - backend.einsum("bij,ajk->abik", basis[:nb_generators], basis[old_length:])
        )
        candidates = backend.reshape(candidates, (-1, dims, dims))
    else:
        if max_iterations > 0:
            log.warning(
                f"Maximum number of iterations ({max_iterations}) reached "
                + "before the Lie closure was complete."
            )
        log.warning(
            f"Maximum number of iterations ({max_iterations}) reached "
            + "before the Lie closure was complete."
        )

    if smallest < 1e3 * tol:
        log.warning(
            "An operator was found to be linearly independent with a residual norm of "
            + f"{smallest:.1e}, close to ``tol`` = {tol:.1e}. It may be numerical noise, "
            + "in which case the algebra is overestimated: try a larger ``tol``."
        )

    return basis


def _lie_closure_pauli_strings(
    generators: list[str], max_iterations: int, backend: Backend | None = None
) -> list[str]:
    """Compute the dynamical Lie algebra generated by Pauli strings.

    The commutator of two Pauli strings is either zero or proportional to their product,
    hence the algebra is spanned by Pauli strings, which are handled as the rows
    :math:`(x | z)` of a tableau: the product is the XOR of two rows, and two Paulis
    anticommute if and only if their symplectic inner product is :math:`1`.

    Args:
        generators (list[str]): Pauli strings of identical length.
        max_iterations (int): maximum nesting depth of commutators.
        backend (:class:`qibo.backends.abstract.Backend`, optional): backend whose engine
            is used in the execution. If ``None``, it uses the current backend.
            Defaults to ``None``.

    Returns:
        list[str]: Pauli strings that span the algebra.
    """
    backend = _check_backend(backend)

    nqubits = len(generators[0])
    if nqubits <= 32:
        return _lie_closure_pauli_strings_packed(generators, max_iterations)

    clifford_backend = CliffordBackend(_get_engine_name(backend))

    # rows of the tableau are the bit vectors (x | z) of the Pauli strings,
    # phases are dropped as they do not affect the span
    tableau = clifford_backend.vstack(
        [clifford_backend._pauli_to_binary(gen, nqubits) for gen in generators]
    )
    _, indices = clifford_backend.unique(tableau, axis=0, return_index=True)
    basis = tableau[sorted(indices)]
    nb_generators = basis.shape[0]
    old_length = 0
    for _ in range(max_iterations):
        new, gens = basis[old_length:], basis[:nb_generators]

        # symplectic inner product, which is 1 for anticommuting Paulis
        anticommute = clifford_backend.mod(
            clifford_backend.matmul(new[:, :nqubits], gens[:, nqubits:].T)
            + clifford_backend.matmul(new[:, nqubits:], gens[:, :nqubits].T),
            2,
        )
        rows, columns = clifford_backend.nonzero(anticommute)

        # [P, Q] is proportional to the product of P and Q if they anticommute
        candidates = clifford_backend.vstack((basis, new[rows] ^ gens[columns]))
        _, indices = clifford_backend.unique(candidates, axis=0, return_index=True)
        indices = sorted(indices[indices >= basis.shape[0]])

        if len(indices) == 0:
            break

        old_length = basis.shape[0]
        basis = clifford_backend.vstack((basis, candidates[indices]))
    else:
        if max_iterations > 0:
            log.warning(
                f"Maximum number of iterations ({max_iterations}) reached "
                + "before the Lie closure was complete."
            )

    # tableau in the Aaronson-Gottesman format: (x | z | phase) plus a scratch row
    tableau = clifford_backend.zeros(
        (basis.shape[0] + 1, 2 * nqubits + 1), dtype=clifford_backend.uint8
    )
    tableau[:-1, : 2 * nqubits] = basis
    paulis, _ = clifford_backend.symplectic_matrix_to_generators(tableau)

    return paulis


def _lie_closure_pauli_strings_packed(
    generators: list[str], max_iterations: int
) -> list[str]:
    """Compute the dynamical Lie algebra generated by Pauli strings on at most :math:`32` qubits.

    Each Pauli string is stored as a pair of unsigned integers :math:`(x, z)`, whose bits are
    the :math:`x` and :math:`z` parts of its tableau row. The product of two Paulis is the
    bitwise XOR of the integers, and two Paulis anticommute if and only if the parity of
    :math:`\\text{popcount}(x_{1} \\, \\& \\, z_{2} \\, \\oplus \\, z_{1} \\, \\& \\, x_{2})`
    is odd. A single integer :math:`x + 2^{n} z` identifies each Pauli, so that duplicates are
    removed by sorting a one-dimensional array.

    Args:
        generators (list[str]): Pauli strings of identical length at most :math:`32`.
        max_iterations (int): maximum nesting depth of commutators.

    Returns:
        list[str]: Pauli strings that span the algebra, in order of discovery.
    """
    nqubits = len(generators[0])
    shift = np.uint64(nqubits)
    weights = np.uint64(1) << np.arange(nqubits, dtype=np.uint64)

    letters = np.frombuffer("".join(generators).encode(), dtype=np.uint8)
    letters = letters.reshape(len(generators), nqubits)
    x_part = ((letters == ord("X")) | (letters == ord("Y"))) @ weights
    z_part = ((letters == ord("Z")) | (letters == ord("Y"))) @ weights

    _, indices = np.unique(x_part | (z_part << shift), return_index=True)
    indices = np.sort(indices)
    x_part, z_part = x_part[indices], z_part[indices]
    gens_x, gens_z = x_part, z_part
    known = np.sort(x_part | (z_part << shift))

    start = 0
    for _ in range(max_iterations):
        new_x, new_z = x_part[start:], z_part[start:]

        # [P, Q] is proportional to the product of P and Q if they anticommute
        overlap = (new_x[:, None] & gens_z) ^ (new_z[:, None] & gens_x)
        rows, columns = np.nonzero(np.bitwise_count(overlap) & 1)
        cand_x = new_x[rows] ^ gens_x[columns]
        cand_z = new_z[rows] ^ gens_z[columns]

        # keep the first occurrence of each candidate that is not yet in the basis
        keys, indices = np.unique(cand_x | (cand_z << shift), return_index=True)
        positions = np.minimum(np.searchsorted(known, keys), len(known) - 1)
        indices = np.sort(indices[known[positions] != keys])

        if len(indices) == 0:
            break

        start = len(x_part)
        x_part = np.concatenate((x_part, cand_x[indices]))
        z_part = np.concatenate((z_part, cand_z[indices]))
        known = np.sort(x_part | (z_part << shift))
    else:
        if max_iterations > 0:
            log.warning(
                f"Maximum number of iterations ({max_iterations}) reached "
                + "before the Lie closure was complete."
            )

    shifts = np.arange(nqubits, dtype=np.uint64)
    x_bits = (x_part[:, None] >> shifts) & np.uint64(1)
    z_bits = (z_part[:, None] >> shifts) & np.uint64(1)
    paulis = np.frombuffer(b"IXZY", dtype=np.uint8)[
        (x_bits + 2 * z_bits).astype(np.intp)
    ]

    return [row.tobytes().decode() for row in paulis]


def _lie_closure_pauli_sums(
    generators: list[str | dict[str, float]],
    max_iterations: int,
    tol: float,
    backend: Backend | None = None,
) -> list[dict[str, float]]:
    """Compute the dynamical Lie algebra generated by real combinations of Pauli strings.

    Operators are coefficient vectors over a table of Pauli strings, which are orthonormal
    under the Hilbert-Schmidt inner product, so that the inner product is the Euclidean one.
    Commutators are computed term by term on the tableau rows :math:`(x | z)` of the Paulis:
    :math:`i [P, Q] = 2 \\, i^{e + 1} R` for anticommuting :math:`P` and :math:`Q`, with
    :math:`R` given by the XOR of the rows and :math:`P \\, Q = i^{e} R`.

    Args:
        generators (list[str or dict]): Pauli strings, or dictionaries mapping Pauli strings
            of identical length to real coefficients.
        max_iterations (int): maximum nesting depth of commutators.
        tol (float): threshold on the norm below which a candidate is considered linearly
            dependent on the current basis.
        backend (:class:`qibo.backends.abstract.Backend`, optional): backend whose engine
            is used in the execution. If ``None``, it uses the current backend.
            Defaults to ``None``.

    Returns:
        list[dict]: Orthonormal basis, each element mapping Pauli strings to coefficients.
    """
    backend = _check_backend(backend)

    terms = [{gen: 1.0} if isinstance(gen, str) else gen for gen in generators]
    strings = [string for term in terms for string in term]
    nqubits = len(strings[0])
    clifford_backend = CliffordBackend(_get_engine_name(backend))

    # rows of the tableau are the bit vectors (x | z) of the Pauli strings,
    # phases are dropped as they do not affect the span
    tableau = clifford_backend.vstack(
        [clifford_backend._pauli_to_binary(string, nqubits) for string in strings]
    )
    words, inverse = clifford_backend.unique(tableau, axis=0, return_inverse=True)

    # coefficients below this threshold are numerical noise and are dropped to keep
    # the vectors sparse. It is orders of magnitude below ``tol``, otherwise
    # the perturbation of the basis would spoil the linear independence check.
    threshold = 1e-3 * tol

    initial = clifford_backend.zeros((len(terms), len(words)), dtype=float)
    owners = [index for index, term in enumerate(terms) for _ in term]
    initial[owners, inverse.reshape(-1)] = [
        float(coeff) for term in terms for coeff in term.values()
    ]

    basis = clifford_backend.zeros((0, len(words)), dtype=float)
    nb_generators, stop = 0, 0
    smallest = math.inf
    for epoch in range(max_iterations + 1):
        # rows of the basis added in the previous round, which are commuted with
        # each of the original generators in this round
        start, stop = stop, basis.shape[0]

        for index in range(1 if epoch == 0 else nb_generators):
            if epoch == 0:
                candidates = initial
            else:
                new, gen = basis[start:stop], basis[index]
                support = clifford_backend.nonzero(
                    clifford_backend.any(new != 0, axis=0)
                )[0]
                columns = clifford_backend.nonzero(gen)[0]
                bits_1, bits_2 = words[support], words[columns]
                anticommute = clifford_backend.mod(
                    clifford_backend.matmul(bits_1[:, :nqubits], bits_2[:, nqubits:].T)
                    + clifford_backend.matmul(
                        bits_1[:, nqubits:], bits_2[:, :nqubits].T
                    ),
                    2,
                )
                rows, cols = clifford_backend.nonzero(anticommute)
                bits_1, bits_2 = bits_1[rows].astype(int), bits_2[cols].astype(int)
                exponents = clifford_backend.sum(
                    _exponent(
                        bits_1[:, :nqubits],
                        bits_1[:, nqubits:],
                        bits_2[:, :nqubits],
                        bits_2[:, nqubits:],
                    ),
                    axis=1,
                )
                signs = clifford_backend.where(exponents % 4 == 1, -2.0, 2.0)

                table, inverse = clifford_backend.unique(
                    bits_1 ^ bits_2, axis=0, return_inverse=True
                )
                if len(table) == 0:
                    continue

                candidates = clifford_backend.zeros(
                    (new.shape[0], len(table)), dtype=float
                )
                clifford_backend.add_at(
                    candidates,
                    (slice(None), inverse.reshape(-1)),
                    new[:, support[rows]] * (gen[columns[cols]] * signs),
                )

                # merge the new Pauli strings into the global table
                merged, inverse = clifford_backend.unique(
                    clifford_backend.vstack((words, table.astype(words.dtype))),
                    axis=0,
                    return_inverse=True,
                )
                inverse = inverse.reshape(-1)
                basis_merged = clifford_backend.zeros(
                    (basis.shape[0], len(merged)), dtype=float
                )
                basis_merged[:, inverse[: len(words)]] = basis
                candidates_merged = clifford_backend.zeros(
                    (candidates.shape[0], len(merged)), dtype=float
                )
                candidates_merged[:, inverse[len(words) :]] = candidates
                words, basis, candidates = merged, basis_merged, candidates_merged

            # Gram-Schmidt, repeated twice for numerical stability: first against
            # the current basis in one shot, then among the surviving candidates
            for _ in range(2):
                candidates = candidates - (candidates @ basis.T) @ basis
            norms = clifford_backend.sqrt(clifford_backend.sum(candidates**2, axis=1))
            added = clifford_backend.zeros((0, len(words)), dtype=float)
            for candidate in candidates[norms > tol]:
                for _ in range(2):
                    candidate = candidate - (added @ candidate) @ added
                norm = clifford_backend.sqrt(clifford_backend.sum(candidate**2))
                if norm > tol:
                    if epoch > 0:
                        smallest = min(smallest, float(norm))
                    candidate = clifford_backend.where(
                        clifford_backend.abs(candidate) > threshold,
                        candidate / norm,
                        0.0,
                    )
                    added = clifford_backend.vstack((added, candidate[None, :]))
            basis = clifford_backend.vstack((basis, added))

        if basis.shape[0] == stop:
            break

        if epoch == 0:
            nb_generators = basis.shape[0]
    else:
        if max_iterations > 0:
            log.warning(
                f"Maximum number of iterations ({max_iterations}) reached "
                + "before the Lie closure was complete."
            )
        log.warning(
            f"Maximum number of iterations ({max_iterations}) reached "
            + "before the Lie closure was complete."
        )

    if smallest < 1e3 * tol:
        log.warning(
            "An operator was found to be linearly independent with a residual norm of "
            + f"{smallest:.1e}, close to ``tol`` = {tol:.1e}. It may be numerical noise, "
            + "in which case the algebra is overestimated: try a larger ``tol``."
        )

    tableau = clifford_backend.zeros(
        (len(words) + 1, 2 * nqubits + 1), dtype=clifford_backend.uint8
    )
    tableau[:-1, : 2 * nqubits] = words
    names, _ = clifford_backend.symplectic_matrix_to_generators(tableau)

    return [
        {
            names[column]: float(element[column])
            for column in clifford_backend.nonzero(element)[0]
        }
        for element in basis
    ]


def _vector_projection(
    vector: ArrayLike, directions: ArrayLike, backend: Backend | None = None
) -> ArrayLike:
    """Return projection(s) of ``vector`` in the direction of vectors in ``directions``.

    Args:
        vector (ArrayLike): vector to be projected.
        directions (ArrayLike): either an :math:`1`-dimensional array corresponding to the
            direction of projection or an array of arrays corresponding to several
            directions.
        backend (:class:`qibo.backends.abstract.Backend`, optional): backend to be
            used in the execution. If ``None``, it uses
            the current backend. Defaults to ``None``.

    Returns:
        ArrayLike: Either one vector projection or a list of several projections.
    """
    if isinstance(directions, list):
        directions = backend.cast(directions, dtype=directions[0].dtype)

    if len(directions.shape) == 1:
        return (
            backend.dot(backend.conj(vector), directions)
            * directions
            / backend.dot(backend.conj(directions), directions)
        )

    dot_products = backend.einsum("j,kj", backend.conj(vector), directions)
    inner_prods = backend.diag(
        backend.einsum("jk,lk", backend.conj(directions), directions)
    )

    return backend.reshape(dot_products / inner_prods, (-1, 1)) * directions
