name: docs

on:
  workflow_dispatch:
  push:
    branches: [master]
    tags:
      - "*"

jobs:
  evaluate-label:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.label_step.outputs.version}}
    steps:
      - name: checks for the label
        id: label_step
        run: |
          if [[ "${{ github.ref  }}" == "refs/heads/master" ]]; then
                echo "version=latest" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ github.ref_type }}" == "branch" ]] && [[ "${{ github.ref  }}" != "refs/heads/master" ]]; then
                exit 1
          fi
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
                echo "version=stable" >> $GITHUB_OUTPUT
          fi

  deploy-docs:
    needs: [evaluate-label]
    uses: qiboteam/workflows/.github/workflows/deploy-ghpages-latest-stable.yml@v1
    with:
      python-version: "3.10"
      package-manager: "poetry"
      dependency-path: "**/poetry.lock"
      trigger-label: "${{needs.evaluate-label.outputs.label}}"
      project: qibo
      poetry-extras: --with docs
