name: docs

on:
  workflow_dispatch:
  push:
    branches: [master]
    tags:
      - "*"

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.classify.outputs.version}}
    steps:
      - id: classify
        uses: qiboteam/workflows/actions/docs/version@uv

  deploy-docs:
    needs: [version]
    uses: qiboteam/workflows/.github/workflows/latest-stable.yml@uv
    with:
      python-version: "3.11"
      trigger-label: "${{needs.version.outputs.version}}"
      project: qibo
      uv-extras: --no-dev --group docs --all-extras
